name: Build and deploy frontend
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn
    - run: yarn compile
    - run: yarn build
    - run: yarn test
    - name: Deploy to Skynet
      uses: SkynetLabs/deploy-to-skynet-action@v2
      with:
        upload-dir: build
        github-token: ${{ secrets.GITHUB_TOKEN }}
        registry-seed: ${{ secrets.REGISTRY_SEED || '' }}
        registry-datakey: ${{ secrets.REGISTRY_DATAKEY || '' }}